In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

/Users/abhishekvats/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [3]:
print(train.info())
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pcl

In [4]:
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [5]:
train.Survived.value_counts(normalize=True)

Survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

In [6]:
train.Survived.value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [7]:
train.Age.value_counts()

Age
24.00    30
22.00    27
18.00    26
19.00    25
28.00    25
         ..
36.50     1
55.50     1
0.92      1
23.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [8]:
train.groupby('Sex')['Survived'].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [9]:
train.groupby('Pclass')['Survived'].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [10]:
train.pivot_table(index = 'Sex', columns = 'Pclass', values = 'Survived')

Pclass         1         2         3
Sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [11]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [12]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [13]:
train.Age.median()

28.0

In [14]:
test['Age'] = test['Age'].fillna(test['Age'].median())

In [15]:
train.Age = train.Age.fillna(train.Age.median())

In [16]:
train.Embarked.mode()

0    S
Name: Embarked, dtype: object

In [17]:
train.Embarked = train.Embarked.fillna(train.Embarked.mode()[0])
test.Embarked = test.Embarked.fillna(test.Embarked.mode()[0])

In [18]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     891 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [19]:
train.drop(['Cabin'],axis =1,inplace=True)

In [20]:
test.drop(['Cabin'], axis = 1, inplace = True)

In [21]:
train.drop(['Ticket'], axis = 1, inplace = True)
test.drop(['Ticket'], axis = 1, inplace = True)

In [22]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Fare         417 non-null    float64
 8   Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(3)
memory usage: 29.5+ KB


In [23]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Fare         891 non-null    float64
 9   Embarked     891 non-null    object 
dtypes: float64(2), int64(5), object(3)
memory usage: 69.7+ KB


In [24]:
test.Fare = test.Fare.fillna(test.Fare.median())

In [25]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Fare         418 non-null    float64
 8   Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(3)
memory usage: 29.5+ KB


In [26]:
## Encoding Categorical Variables
train['Sex'] = train.Sex.map({'male':0, 'female': 1})
test['Sex'] = test.Sex.map({'male':0, 'female': 1})

In [27]:
train.Embarked = train.Embarked.map({'S':0, 'C': 1, 'Q':2})
test.Embarked = test.Embarked.map({'S':0, 'C': 1, 'Q':2})

In [28]:
feature_cols = ["Pclass", "Sex", "Age", "SibSp", "Parch", "Embarked"]
train[feature_cols].isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Embarked    0
dtype: int64

In [29]:
X = train[feature_cols]
y =train['Survived']

In [30]:
X_train, X_val, y_train, y_val = train_test_split(X,y,test_size=0.2, random_state = 42)

In [31]:
X.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Sex       891 non-null    int64  
 2   Age       891 non-null    float64
 3   SibSp     891 non-null    int64  
 4   Parch     891 non-null    int64  
 5   Embarked  891 non-null    int64  
dtypes: float64(1), int64(5)
memory usage: 41.9 KB


In [32]:
log_reg = LogisticRegression(max_iter=1000)

In [33]:
log_reg.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [34]:
log_reg.coef_, log_reg.intercept_

(array([[-1.05195202,  2.57981422, -0.03141889, -0.285947  , -0.06496228,
          0.25390969]]),
 array([1.89633303]))

In [35]:
from sklearn.metrics import accuracy_score

In [36]:
y_val_predict = log_reg.predict(X_val)

In [37]:
accuracy = accuracy_score(y_val, y_val_predict)

In [38]:
accuracy

0.8044692737430168

In [39]:
from sklearn.metrics import confusion_matrix, classification_report

In [40]:
cm = confusion_matrix(y_val, y_val_predict)

In [41]:
print(cm)

[[90 15]
 [20 54]]


In [42]:
print(classification_report(y_val,y_val_predict))

              precision    recall  f1-score   support

           0       0.82      0.86      0.84       105
           1       0.78      0.73      0.76        74

    accuracy                           0.80       179
   macro avg       0.80      0.79      0.80       179
weighted avg       0.80      0.80      0.80       179



In [43]:
## Test data
feature_cols = ["Pclass", "Sex", "Age", "SibSp", "Parch", "Embarked"]

In [44]:
X = train[feature_cols]
y = train['Survived']

In [45]:
log_reg = LogisticRegression(max_iter= 1000)
log_reg.fit(X,y)

LogisticRegression(max_iter=1000)

In [46]:
##Predict on the test data set using the exact same features for which we train the data 
X_test = test[feature_cols]

In [47]:
test_preds = log_reg.predict(X_test)

In [48]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    int64  
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Fare         418 non-null    float64
 8   Embarked     418 non-null    int64  
dtypes: float64(2), int64(6), object(1)
memory usage: 29.5+ KB


In [49]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Sex       891 non-null    int64  
 2   Age       891 non-null    float64
 3   SibSp     891 non-null    int64  
 4   Parch     891 non-null    int64  
 5   Embarked  891 non-null    int64  
dtypes: float64(1), int64(5)
memory usage: 41.9 KB


In [50]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Sex       891 non-null    int64  
 2   Age       891 non-null    float64
 3   SibSp     891 non-null    int64  
 4   Parch     891 non-null    int64  
 5   Embarked  891 non-null    int64  
dtypes: float64(1), int64(5)
memory usage: 41.9 KB


In [51]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    int64  
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Fare         418 non-null    float64
 8   Embarked     418 non-null    int64  
dtypes: float64(2), int64(6), object(1)
memory usage: 29.5+ KB


In [52]:
#Build the submission dataframe
submission_titanic = pd.DataFrame({
    "PassengerId":test.PassengerId,
    "Survived": test_preds   
})

In [53]:
submission_titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
dtypes: int64(2)
memory usage: 6.7 KB


In [54]:
submission_titanic.to_csv("submission_titanic.csv", index = False)

In [55]:
## Feature Engineering
train['Family Size'] = train.SibSp + train.Parch + 1
test['Family Size'] = test.SibSp + test.Parch + 1

In [56]:
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    0  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1   
2                               Heikkinen, Miss. Laina    1  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1   
4                             Allen, Mr. William Henry    0  35.0      0   
..                                                 ...  ...   ...    ...   
886                              Montvila, Rev. Juozas    0  27.0      0   
887                       Graham, Miss. Margaret Edith    1  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"    1  28.0      1   
889                              Behr, Mr. Karl Howell    0  26.0      0   
890                                Dooley, Mr. Patrick    0  32.0      0   

     Parch     Fare  Embarked  Family Size  
0        0   7.2500         0            2  
1        0  71.2833         1            2  
2        0   7.9250         0            1  
3        0  53.1000         0            2  
4        0   8.0500         0            1  
..     ...      ...       ...          ...  
886      0  13.0000         0            1  
887      0  30.0000         0            1  
888      2  23.4500         0            4  
889      0  30.0000         1            1  
890      0   7.7500         2            1  

[891 rows x 11 columns]

In [57]:
train.rename(columns = {"Family Size" : "FamilySize"}, inplace = True)

In [58]:
test.rename(columns = {"Family Size" : "FamilySize"} , inplace = True)

In [59]:
train.groupby('FamilySize')['Survived'].mean()

FamilySize
1     0.303538
2     0.552795
3     0.578431
4     0.724138
5     0.200000
6     0.136364
7     0.333333
8     0.000000
11    0.000000
Name: Survived, dtype: float64

In [60]:
train['IsAlone'] = (train.FamilySize==1).astype(int)

In [61]:
test['IsAlone'] = (test.FamilySize==1).astype(int)

In [62]:
train.groupby('IsAlone')['Survived'].mean()

IsAlone
0    0.505650
1    0.303538
Name: Survived, dtype: float64

In [63]:
feature_cols = ["Pclass", "Sex", "Age", "Embarked","FamilySize","IsAlone"]
X = train[feature_cols]
y = train['Survived']

In [64]:
X_train, X_val, y_train, y_val = train_test_split(X,y,test_size=0.2, random_state=42)

In [65]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 712 entries, 331 to 102
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Pclass      712 non-null    int64  
 1   Sex         712 non-null    int64  
 2   Age         712 non-null    float64
 3   Embarked    712 non-null    int64  
 4   FamilySize  712 non-null    int64  
 5   IsAlone     712 non-null    int64  
dtypes: float64(1), int64(5)
memory usage: 38.9 KB


In [66]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    int64  
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Fare         418 non-null    float64
 8   Embarked     418 non-null    int64  
 9   FamilySize   418 non-null    int64  
 10  IsAlone      418 non-null    int64  
dtypes: float64(2), int64(8), object(1)
memory usage: 36.1+ KB


In [67]:
log_reg = LogisticRegression(max_iter=1000)

In [68]:
log_reg.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [69]:
## predict the new values using the feature engineering variables
y_val_pred = log_reg.predict(X_val)

In [70]:
accuracy = accuracy_score(y_val, y_val_pred)

In [71]:
accuracy

0.8100558659217877

In [72]:
cm = confusion_matrix(y_val,y_val_pred)

In [73]:
cm

array([[92, 13],
       [21, 53]])

In [74]:
log_reg = LogisticRegression(max_iter=1000)

## training the model using the whole data set 
log_reg.fit(X,y)

LogisticRegression(max_iter=1000)

In [75]:
X_test = test[feature_cols]

In [76]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Pclass      418 non-null    int64  
 1   Sex         418 non-null    int64  
 2   Age         418 non-null    float64
 3   Embarked    418 non-null    int64  
 4   FamilySize  418 non-null    int64  
 5   IsAlone     418 non-null    int64  
dtypes: float64(1), int64(5)
memory usage: 19.7 KB


In [77]:
## now predicting using the test data set
test_pred_new = log_reg.predict(X_test)

In [78]:
new_submission_titanic = pd.DataFrame({
    "PassengerId" : test.PassengerId,
    "Survived" : test_pred_new
})

In [79]:
new_submission_titanic.to_csv("new_submission_titanic.csv", index = False)

In [80]:
train['Title'] = train.Name.str.extract(r',\s*([A-Za-z]+)\.', expand=False)

In [81]:
test['Title'] = test.Name.str.extract(r',\s*([A-Za-z]+)\.', expand=False)

In [82]:
train['Title'].value_counts()

Title
Mr          517
Miss        182
Mrs         125
Master       40
Dr            7
Rev           6
Major         2
Mlle          2
Col           2
Don           1
Mme           1
Ms            1
Lady          1
Sir           1
Capt          1
Jonkheer      1
Name: count, dtype: int64

In [83]:
train[train['Title'].isnull()]

PassengerId  Survived  Pclass  \
759          760         1       1   

                                                  Name  Sex   Age  SibSp  \
759  Rothes, the Countess. of (Lucy Noel Martha Dye...    1  33.0      0   

     Parch  Fare  Embarked  FamilySize  IsAlone Title  
759      0  86.5         0           1        1   NaN

In [84]:
train.loc[train['PassengerId'] == 760, 'Title'] = 'The Countess'

In [85]:
test.loc[test['PassengerId'] == 760, 'Title'] = 'The Countess'

In [90]:
train['Title'] = train['Title'].replace({
    'Mlle': 'Noble',
    'Ms': 'Miss',
    'Mme': 'Noble',
    'Lady': 'Noble',
    'The Countess': 'Noble',
    'Sir': 'Noble',
    'Don': 'Noble',
    'Jonkheer': 'Noble',
    'Dona': 'Noble',
    'Col': 'Noble',
    'Major': 'Noble',
    'Dr': 'Noble',
    'Rev': 'Noble',
    'Capt': 'Noble'
})

In [91]:
test['Title'] = test['Title'].replace({
    'Mlle': 'Noble',
    'Ms': 'Miss',
    'Mme': 'Noble',
    'Lady': 'Noble',
    'The Countess': 'Noble',
    'Sir': 'Noble',
    'Don': 'Noble',
    'Jonkheer': 'Noble',
    'Dona': 'Noble',
    'Col': 'Noble',
    'Major': 'Noble',
    'Dr': 'Noble',
    'Rev': 'Noble',
    'Capt': 'Noble'
})

In [92]:
train['Title'].value_counts()

Title
Mr        517
Miss      183
Mrs       125
Master     40
Noble      26
Name: count, dtype: int64

In [93]:
train.Title = train.Title.astype('category').cat.codes

In [94]:
test.Title = test.Title.astype('category').cat.codes

In [95]:
train.Title.value_counts()

Title
2    517
1    183
3    125
0     40
4     26
Name: count, dtype: int64

In [96]:
feature_cols = ["Pclass", "Sex", "Age", "Embarked","FamilySize","IsAlone", "Title"]


In [97]:
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    0  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1   
2                               Heikkinen, Miss. Laina    1  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1   
4                             Allen, Mr. William Henry    0  35.0      0   
..                                                 ...  ...   ...    ...   
886                              Montvila, Rev. Juozas    0  27.0      0   
887                       Graham, Miss. Margaret Edith    1  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"    1  28.0      1   
889                              Behr, Mr. Karl Howell    0  26.0      0   
890                                Dooley, Mr. Patrick    0  32.0      0   

     Parch     Fare  Embarked  FamilySize  IsAlone  Title  
0        0   7.2500         0           2        0      2  
1        0  71.2833         1           2        0      3  
2        0   7.9250         0           1        1      1  
3        0  53.1000         0           2        0      3  
4        0   8.0500         0           1        1      2  
..     ...      ...       ...         ...      ...    ...  
886      0  13.0000         0           1        1      4  
887      0  30.0000         0           1        1      1  
888      2  23.4500         0           4        0      1  
889      0  30.0000         1           1        1      2  
890      0   7.7500         2           1        1      2  

[891 rows x 13 columns]

In [98]:
X = train[feature_cols]
y = train['Survived']

In [99]:
X_train, X_val, y_train, y_val = train_test_split(X,y, test_size= 0.2, random_state=42)

In [100]:
log_reg_new = LogisticRegression(max_iter=1000)

In [101]:
log_reg_new.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [102]:
##predict
y_val_pred = log_reg_new.predict(X_val)

In [103]:
accuracy = accuracy_score(y_val,y_val_pred)

In [104]:
accuracy

0.8156424581005587

In [105]:
confusion = confusion_matrix(y_val, y_val_pred)

In [106]:
confusion

array([[92, 13],
       [20, 54]])

In [107]:
## Train on the full train dataset to test on the test set
X = train[feature_cols]
y = train['Survived']

In [108]:
X_test = test[feature_cols]

In [109]:
log_reg_new.fit(X,y)

LogisticRegression(max_iter=1000)

In [110]:
## Getting the prediction for the test set
test_preds_new = log_reg_new.predict(X_test)

In [111]:
submission_titanic_new2 = pd.DataFrame({
    "PassengerId" : test.PassengerId,
    "Survived" : test_preds_new
})

In [115]:
submission_titanic_new2.to_csv('submission_titanic_new3.csv',index = False)

In [116]:
train.head(30)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   
20           21         0       2   
21           22         1       2   
22           23         1       3   
23           24         1       1   
24           25         0       3   
25           26         1       3   
26           27         0       3   
27           28         0       1   
28           29         1       3   
29           30         0       3   

                                                 Name  Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    0  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1   
2                              Heikkinen, Miss. Laina    1  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1   
4                            Allen, Mr. William Henry    0  35.0      0   
5                                    Moran, Mr. James    0  28.0      0   
6                             McCarthy, Mr. Timothy J    0  54.0      0   
7                      Palsson, Master. Gosta Leonard    0   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)    1  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)    1  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut    1   4.0      1   
11                           Bonnell, Miss. Elizabeth    1  58.0      0   
12                     Saundercock, Mr. William Henry    0  20.0      0   
13                        Andersson, Mr. Anders Johan    0  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina    1  14.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)     1  55.0      0   
16                               Rice, Master. Eugene    0   2.0      4   
17                       Williams, Mr. Charles Eugene    0  28.0      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...    1  31.0      1   
19                            Masselmani, Mrs. Fatima    1  28.0      0   
20                               Fynney, Mr. Joseph J    0  35.0      0   
21                              Beesley, Mr. Lawrence    0  34.0      0   
22                        McGowan, Miss. Anna "Annie"    1  15.0      0   
23                       Sloper, Mr. William Thompson    0  28.0      0   
24                      Palsson, Miss. Torborg Danira    1   8.0      3   
25  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...    1  38.0      1   
26                            Emir, Mr. Farred Chehab    0  28.0      0   
27                     Fortune, Mr. Charles Alexander    0  19.0      3   
28                      O'Dwyer, Miss. Ellen "Nellie"    1  28.0      0   
29                                Todoroff, Mr. Lalio    0  28.0      0   

    Parch      Fare  Embarked  FamilySize  IsAlone  Title  
0       0    7.2500         0           2        0      2  
1       0   71.2833         1           2        0      3  
2       0    7.9250         0           1        1      1  
3       0   53.1000         0           2        0      3  
4       0    8.0500         0           1        1      2  
5       0    8.4583         2           1        1      2  
6       0   51.8625         0           1        1      2  
7       1   21.0750         0           5        0

In [117]:
train.groupby('Title')['Survived'].mean()

Title
0    0.575000
1    0.699454
2    0.156673
3    0.792000
4    0.423077
Name: Survived, dtype: float64

In [118]:
from sklearn.ensemble import RandomForestClassifier

In [125]:
X = train[feature_cols]
y =train['Survived']

In [126]:
X_train, X_val, y_train, y_val = train_test_split(X,y, test_size=0.2, random_state=42)

In [127]:
rf = RandomForestClassifier(
    n_estimators=300,
    max_depth = 5,
    min_samples_split=10,
    min_samples_leaf=4,
    random_state=42
)

In [128]:
y_train.info()

<class 'pandas.core.series.Series'>
Index: 712 entries, 331 to 102
Series name: Survived
Non-Null Count  Dtype
--------------  -----
712 non-null    int64
dtypes: int64(1)
memory usage: 11.1 KB


In [129]:
rf.fit(X_train,y_train)

RandomForestClassifier(max_depth=5, min_samples_leaf=4, min_samples_split=10,
                       n_estimators=300, random_state=42)

In [130]:
y_val_pred = rf.predict(X_val)

In [131]:
accuracy = accuracy_score(y_val,y_val_pred)

In [132]:
accuracy

0.8100558659217877

In [133]:
cm = confusion_matrix(y_val, y_val_pred)

In [134]:
cm

array([[92, 13],
       [21, 53]])

In [135]:
rf.fit(X,y)

RandomForestClassifier(max_depth=5, min_samples_leaf=4, min_samples_split=10,
                       n_estimators=300, random_state=42)

In [136]:
X_test = test[feature_cols]

In [138]:
test_pred = rf.predict(X_test)

In [140]:
submission_new_4 = pd.DataFrame({
    "PassengerId": test.PassengerId,
    "Survived" : test_pred
})

In [141]:
submission_new_4.to_csv("submission_4.csv", index = False)